### ISSUE TITLE
Tear out put back and tear out again is bugged

### ISSUE THREAD

**Issue by bjedrzejewski** [owennw/OpenFinD3FC#119]
You can replicate and see that the second time you tear out the same window it doesn't work well. On third try it works again.

**Comment by owennw** [comment]
Yes it's a bit broken, I was intending on toggling that feature off if we merge before it's fixed.

**Comment by owennw** [comment]
I'll close this since the tearout branch is in production and so doesn't really have bugs yet..

**Comment by bjedrzejewski** [comment]
Good point, its just unfinished.
