### ISSUE TITLE
It needs to be possible to un-fav from fav section

### ISSUE THREAD

**Issue by bjedrzejewski** [owennw/OpenFinD3FC#120]
This is a comment mentioned by Colin during the meeting.

**Comment by owennw** [comment]
Meeting today? Or a previous one. I was thinking we should have a system for this, but it perhaps needs to wait on a UX design?

**Comment by bjedrzejewski** [comment]
UX design would be needed, for now we can move it to a later release?

**Comment by bjedrzejewski** [comment]
This includes:

![image](https://cloud.githubusercontent.com/assets/9947570/12111986/6a5dca6e-b391-11e5-8310-e33c140be43c.png)

**Comment by owennw** [comment]
There's currently a branch with the notification symbol, and a favourite star implemented on the search tab. I'd be in favour of not duplicating this code so if we can create some sort of toggle-icon that can be re-used that would be good.

**Comment by owennw** [comment]
Closed by #137. Haven't implemented the designed confirmation window yet, but using the built-in confirm window.
