### ISSUE TITLE
Clicking logo should restore application to a startup state

### ISSUE THREAD

**Issue by owennw** [owennw/OpenFinD3FC#156]
i.e. clear the search, remove the selection and go back to the favourites tab.

**Comment by bjedrzejewski** [comment]
I am not sure anymore if this is a good idea. Since we are doing the tearout the design of clicking to get the initial state seems bad. Thoughts? Close?

**Comment by owennw** [comment]
Hmm. Yeah until someone wants it we don't need it. Close.
