### ISSUE TITLE
Style showcase chart closer to the design

### ISSUE THREAD

**Issue by owennw** [owennw/OpenFinD3FC#181]
This can be broken into smaller issues if required.

**Comment by bjedrzejewski** [comment]
RSI dash frequency is wrong
gridlines should have a lower opacity
the line between tiles is too strong
y axis labels are the wrong colour and look like the font size is too large
The spot price callout is styled differently
There should be a dark vertical line next to the search slide-out panel
The mini-charts should have a dot at the end
The vertical spacing between the numbers on the tiles bottom-right is incorrect
The Scott Logic logo looks a bit too big??

These are the issues mentioned in the email. Lets do them all here.

**Comment by bjedrzejewski** [comment]
I think we need Rui to update his designs quite a bit, to tell us with more details what he is expecting.

**Comment by owennw** [comment]
Yes I think so too.

**Comment by bjedrzejewski** [comment]
Didn't you add that dot in the end?

**Comment by owennw** [comment]
Dot?

**Comment by owennw** [comment]
Oh the minichart dot. No I didn't actually.

**Comment by owennw** [comment]
I'll close this as we'll give Rui the current state and he'll draw up a new list of changes (or not.. !)
