### ISSUE TITLE
Showcase now doesn't use quandl API key

### ISSUE THREAD

**Issue by owennw** [owennw/OpenFinD3FC#193]

**Comment by bjedrzejewski** [comment]
This was fixed on my branch, can be a quick fix in James on.

**Comment by owennw** [comment]
This:

> `+        historicFeed.apiKey('kM9Z9aEULVDD7svZ4A8B');`?

**Comment by owennw** [comment]
Can you take a look at this? You seem to have an idea of the best way to approach it.

Also we should look at which fork/version of the showcase we're using. Has James' personal branch been merged into main? Should your branch be updated?

**Comment by bjedrzejewski** [comment]
Yeah, it will require me forking James branch, which is fine.

**Comment by bjedrzejewski** [comment]
I will do it later today.

**Comment by owennw** [comment]
Fixed by #256
