### ISSUE TITLE
Move less files into correct folders

### ISSUE THREAD

**Issue by owennw** [owennw/OpenFinD3FC#195]

**Comment by bjedrzejewski** [comment]
Thats duplicate, sub-issue of less refactor

**Comment by owennw** [comment]
Hmm, I was thinking of just doing this bit now, makes the other issue a bit smaller? Whatever you like though.

**Comment by bjedrzejewski** [comment]
Its sort of a prerequisite, first step.

**Comment by bjedrzejewski** [comment]
Yeah, its good, we can do this quickly to set the scene.

**Comment by owennw** [comment]
Closed by #197
