### ISSUE TITLE
Release 5 - Series and indicator dropdown menus don't open

### ISSUE THREAD

**Issue by jleft** [owennw/OpenFinD3FC#257]
Clicking on the series and indicator selector buttons does not open the dropdown menus (which is the expected behaviour).

These dropdowns use Bootstrap's JS, which was removed in c8749cdb6fd90e67fbbdd124ed2460358970a4d3.

Bootstrap's JavaScript, or just the Bootstrap's dropdown JavaScript, needs to be included for the showcase to function properly; this would fix it: 9ae08507357a33ad5511667242b70f4ba6f9daf8.

**Comment by owennw** [comment]
Will merge fix and create a release 5.1.
