### ISSUE TITLE
Create start page

### ISSUE THREAD

**Issue by owennw** [owennw/OpenFinD3FC#3]
Create an empty start page, not wired into anything, as per the balsamiq mock up.

**Comment by bjedrzejewski** [comment]
I will start on that based on the balsamiq here:

![main page](https://cloud.githubusercontent.com/assets/9947570/11564550/b38c6710-99d1-11e5-9df1-8421419e9151.png)

**Comment by owennw** [comment]
If you could start it so it's just a shell with a button and push that as a sub-feature then you can continue to style and enhance it while I work on opening a new open window from that button. That way the 'open new window' code can be silo'd maybe and moved if we change the layout.
