### ISSUE TITLE
Tweak app styling as per new design

### ISSUE THREAD

**Issue by owennw** [owennw/OpenFinD3FC#308]

**Comment by owennw** [comment]
@WPFerg Did you look at "The dropdowns could be closer to their respective buttons (5px margin)." too?

**Comment by WPFerg** [comment]
I thought it meant the text next to the icon, which I changed over to the 5px margin

**Comment by owennw** [comment]
Hmm I thought it meant the placement of the drop down windows with respect to their button (i.e. they should be placed higher up).

**Comment by WPFerg** [comment]
Ohh, I see, I'll see what I can do

**Comment by WPFerg** [comment]
Fixed by #317
