### ISSUE TITLE
Remove broken watch task

### ISSUE THREAD

**Issue by owennw** [owennw/OpenFinD3FC#38]

**Comment by owennw** [comment]
Sadly it seems that it's not possible to have a working `watch` run after our `openfin:serve`. The watch task runs but doesn't seem to notice changes. Conversely, when you first run a `watch` task and poke some changes to trigger a serve, this seems to work. Closing the window and making changes does trigger the watch.

However having to poke the files to run the project isn't satisfactory, so I'd rather remove the `watch` task altogether.

**Comment by bjedrzejewski** [comment]
Unless we find a fix. Maybe we leave it as optional with comment for now? And then someone fixes it?

**Comment by owennw** [comment]
It's in our history, we can resurrect it quickly if we want to try it again. Otherwise it's just broken code?

**Comment by bjedrzejewski** [comment]
Good point. Lets clean it
