### ISSUE TITLE
Public directory should be completely built, not versioned.

### ISSUE THREAD

**Issue by bjedrzejewski** [owennw/OpenFinD3FC#67]

**Comment by owennw** [comment]
Is the idea here to throw all of our code into the src folder, and (for now) copy it into the public folder?

**Comment by bjedrzejewski** [comment]
Copy, minify, lint, everything

**Comment by owennw** [comment]
#51 takes care of much of that. What I was stressing was: from 'src'?

**Comment by bjedrzejewski** [comment]
Yes, from src

**Comment by owennw** [comment]
Closed by #99
