### ISSUE TITLE
Scroll on search results

### ISSUE THREAD

**Issue by bjedrzejewski** [owennw/OpenFinD3FC#73]

**Comment by owennw** [comment]
Until we have a design it might be worth holding off on this to save effort.

**Comment by owennw** [comment]
I reckon we want to introduce this now, for this release.

**Comment by owennw** [comment]
@bjedrzejewski How do we want these to work? My thinking is that the vertical scrollbar only appears when necessary, and there won't be a horizontal one. Obviously a vertical scrollbar will take up width -- how do we handle that?

**Comment by bjedrzejewski** [comment]
@owennw I will do this one.
