### ISSUE TITLE
Handle 404 better. Make 404 impossible with search terms.

### ISSUE THREAD

**Issue by bjedrzejewski** [owennw/OpenFinD3FC#92]
User should be able to recover from 404. Possibly being shown the homepage/dashboard with an explanation why 404 happened. 404 should not happen with any search terms.

Search terms could simply disallow some characters that are problematic.

**Comment by owennw** [comment]
Is this relevant with our current design?

**Comment by bjedrzejewski** [comment]
This is not an issue in the new design.
